<a href="https://colab.research.google.com/github/IshaanMhalgi1/mlassignments/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 1

In [ ]:
import pandas as pd
import numpy as np

Importing CSV file

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

Find shape of data

In [ ]:
df.shape

(3000, 9)

Find missing values

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

Finding datatypes of columns

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

Finding number of zeros

In [ ]:
(df == 0).sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

Indexing selecting data and sorting

In [ ]:
df['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
df[['total_rooms','median_house_value']]

      total_rooms  median_house_value
0          3885.0            344700.0
1          1510.0            176500.0
2          3589.0            270500.0
3            67.0            330000.0
4          1241.0             81700.0
...           ...                 ...
2995       1450.0            225000.0
2996       5257.0            237200.0
2997        956.0             62000.0
2998         96.0            162500.0
2999       1765.0            500001.0

[3000 rows x 2 columns]

In [ ]:
df.iloc[3:4]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0

In [ ]:
df[df['total_rooms']<100]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
564,-121.98,37.14,37.0,74.0,19.0,63.0,17.0,9.5908,350000.0
641,-121.04,37.67,16.0,19.0,19.0,166.0,9.0,0.5360,162500.0
666,-121.89,37.42,26.0,40.0,8.0,52.0,7.0,7.7197,225000.0
733,-117.99,33.81,46.0,38.0,8.0,66.0,14.0,4.1667,162500.0
740,-117.12,32.66,52.0,16.0,4.0,8.0,3.0,1.1250,60000.0
742,-122.22,37.88,20.0,95.0,13.0,31.0,15.0,2.4444,475000.0
826,-118.25,34.06,20.0,41.0,17.0,87.0,25.0,1.5491,225000.0
842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
1202,-117.30,34.10,49.0,60.0,11.0,76.0,13.0,2.5625,75000.0
1345,-121.29,37.33,36.0,48.0,12.0,27.0,8.0,4.0000,75000.0
1355,-117.11,32.66,52.0,25.0,5.0,14.0,9.0,1.6250,118800.0
1356,-121.90,37.39,42.0,42.0,14.0,26.0,14.0,1.7361,500001.0
1453,-122.28,37.80,52.0,96.0,31.0,191.0,34.0,0.7500,162500.0
1509,-119.02,35.38,52.0,90.0,35.0,36.0,31.0,0.8054,60000.0
1539,-120.79,37.08,9.0,97.0,20.0,91.0,22.0,2.9063,55000.0
1726,-117.05,33.03,16.0,87.0,20.0,32.0,21.0,4.3571,144600.0
1902,-117.90,36.95,19.0,99.0,26.0,51.0,22.0,1.7292,137500.0
2132,-121.84,36.62,26.0,32.0,8.0,27.0,10.0,2.2250,150000.0
2494,-118.44,34.04,49.0,32.0,7.0,14.0,7.0,2.1875,225000.0
2502,-118.23,33.76,21.0,49.0,14.0,29.0,16.0,5.0000,87500.0
2636,-120.92,37.63,39.0,45.0,8.0,22.0,9.0,1.7679,450000.0
2640,-114.62,33.62,26.0,18.0,3.0,5.0,3.0,0.5360,275000.0
2690,-118.06,34.03,36.0,21.0,7.0,21.0,9.0,2.3750,175000.0
2768,-122.49,38.00,26.0,48.0,8.0,19.0,8.0,7.7197,400000.0
2879,-121.84,38.02,46.0,66.0,22.0,37.0,21.0,0.5360,87500.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0

Sort Data

In [ ]:
df.sort_values(by='median_house_value')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2001,-117.16,32.71,52.0,845.0,451.0,1230.0,375.0,1.0918,22500.0
1031,-123.08,40.40,10.0,365.0,102.0,140.0,49.0,1.7969,37500.0
2740,-119.97,36.44,18.0,1128.0,237.0,772.0,220.0,2.1771,39200.0
734,-117.65,35.00,36.0,1184.0,316.0,672.0,241.0,1.9107,39800.0
2555,-122.06,37.39,22.0,1236.0,290.0,413.0,274.0,3.6875,40000.0
...,...,...,...,...,...,...,...,...,...
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0
2152,-118.43,33.96,20.0,1901.0,270.0,704.0,254.0,8.7819,500001.0
2992,-122.33,37.39,52.0,573.0,102.0,232.0,92.0,6.2263,500001.0
2968,-119.23,34.17,18.0,6171.0,1490.0,2164.0,1210.0,3.6875,500001.0
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0

Describe data

In [ ]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

Check Data types again

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

Counting unique values, format and data type conversion

In [ ]:
df.nunique()

longitude              607
latitude               587
housing_median_age      52
total_rooms           2215
total_bedrooms        1055
population            1802
households            1026
median_income         2578
median_house_value    1784
dtype: int64

In [ ]:
df['population'].value_counts()

population
870.0     7
753.0     6
697.0     6
881.0     6
1211.0    6
         ..
2153.0    1
2227.0    1
1780.0    1
299.0     1
1186.0    1
Name: count, Length: 1802, dtype: int64

Convert integer to float

In [ ]:
df['total_bedrooms'] = df['total_bedrooms'].astype(float)
df['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
df['median_income'] = df['median_income'].astype(int)
df['median_income']

0       6
1       3
2       5
3       6
4       2
       ..
2995    1
2996    3
2997    2
2998    3
2999    8
Name: median_income, Length: 3000, dtype: int64